model_list:
  - model_name: openai/*
    litellm_params:
      model: openai/*
  - model_name: aiml/*
    litellm_params:
      model: aiml/*
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: cerebras/*
    litellm_params:
      model: cerebras/*
  - model_name: cohere/*
    litellm_params:
      model: cohere/*
  - model_name: databricks/*
    litellm_params:
      model: databricks/*
  - model_name: deepinfra/*
    litellm_params:
      model: deepinfra/*
  - model_name: deepgram/*
    litellm_params:
      model: deepgram/*
  - model_name: deepseek/*
    litellm_params:
      model: deepseek/*
  - model_name: fireworks_ai/*
    litellm_params:
      model: fireworks_ai/*
  - model_name: gemini/*
    litellm_params:
      model: gemini/*
  - model_name: groq/*
    litellm_params:
      model: groq/*
  - model_name: jina_ai/*
    litellm_params:
      model: jina_ai/*
  - model_name: mistral/*
    litellm_params:
      model: mistral/*
  - model_name: openrouter/*
    litellm_params:
      model: openrouter/*
  - model_name: oci/*
    litellm_params:
      model: oci/*
  - model_name: perplexity/*
    litellm_params:
      model: perplexity/*
  - model_name: sambanova/*
    litellm_params:
      model: sambanova/*
  - model_name: together_ai/*
    litellm_params:
      model: together_ai/*
  - model_name: volcengine/*
    litellm_params:
      model: volcengine/*
  - model_name: voyage/*
    litellm_params:
      model: voyage/*
  - model_name: xai/*
    litellm_params:
      model: xai/*

router_settings:
  routing_strategy: simple-shuffle
  cooldown_time: 1

litellm_settings:
  request_timeout: 600 # raise Timeout error if call takes longer than 600 seconds. Default value is 6000seconds if not set
  set_verbose: False # Switch off Debug Logging, ensure your logs do not have any debugging on
  json_logs: true # Get debug logs in json format
  drop_params: True
  callbacks: proxy_handler.proxy_handler_instance # sets litellm.callbacks = [proxy_handler_instance]
  cache: True
  cache_params:
    type: disk
    disk_cache_dir: ./litellm-cache

general_settings:
  custom_auth: proxy_auth.user_api_key_auth
