# ============================================================================
# Model List - Simplified with Wildcard
# ============================================================================
model_list:
  # DeepSeek with reasoning support
  - model_name: deepseek/*
    litellm_params:
      model: deepseek/*
      supports_response_schema: True # Enable schema validation

  # Universal wildcard - all models will be handled by pre_call_hook
  - model_name: "*"
    litellm_params:
      model: "*"
      # No max_retries here - let HTTP client handle retries
      # No api_key here - injected by pre_call_hook

# ============================================================================
# Router Settings
# ============================================================================
router_settings:
  routing_strategy: simple-shuffle
  cooldown_time: 0 # No cooldown needed for single wildcard model
  num_retries: 0 # Retries handled by HTTP client layer
  timeout: 600 # Match request_timeout

  # Redis for distributed routing (optional, for multi-instance)
  # redis_host: localhost
  # redis_port: 6379
  # redis_password: ${REDIS_PASSWORD}

# ============================================================================
# LiteLLM Settings - Production Optimized
# ============================================================================
litellm_settings:
  # Timeouts
  request_timeout: 1800 # 30 minutes for long-running requests

  # Logging
  set_verbose: False # Disable verbose logging in production
  json_logs: True # Structured JSON logs

  # Parameter Handling
  drop_params: True # Drop unsupported params (important for compatibility)

  # Callbacks
  callbacks: proxy_handler.proxy_handler_instance

  # Caching
  cache: True
  cache_params:
    type: disk
    disk_cache_dir: ./litellm-cache
    ttl: 3600 # Cache TTL: 1 hour

  # Performance
  num_retries: 0 # Disable LiteLLM retries (use HTTP client retries)
  fallback_models: [] # No fallbacks - handled by routing

  # Error Handling
  allowed_fails: 0 # Fail fast

  # Rate Limiting (optional)
  # max_parallel_requests: 1000
  # max_queue_size: 5000

# ============================================================================
# General Settings
# ============================================================================
general_settings:
  # Custom Authentication
  custom_auth: proxy_auth.user_api_key_auth

  # Database (optional - for persistent key management)
  # database_url: ${DATABASE_URL}
  # database_type: postgresql

  # Master Key (optional - for admin API)
  # master_key: ${LITELLM_MASTER_KEY}

  # CORS (if serving web clients)
  # allowed_origins: ["https://your-app.com"]

  # Health Check
  # health_check_interval: 60
