@echo off
setlocal

echo Changing to the target directory...
cd ../../../

echo Checking if virtual environment already exists...
if exist .venv (
    echo .venv already exists, skipping creation.
) else (
    echo Creating Python virtual environment...
    py -m venv .venv
)

echo Activating virtual environment...
call .\.venv\Scripts\activate.bat

echo Installing dependencies...
pip install -r requirements-windows.txt

echo Setting environment variables...
set FP_APP_BASE_URL=https://www.flexiproxy.com
set FP_PROXY_SERVER_URL=https://test.flexiproxy.com
set FP_PROXY_SERVER_ADVANCED=0
set FP_PROXY_SERVER_KEYPAIR_DIR=../key
set /p FP_APP_TOKEN_PASS="[FP_APP_TOKEN_PASS] Issued by flexi-proxy admin/token-issuance.ts: "
set /p FP_PROXY_SERVER_ID="[FP_PROXY_SERVER_ID] Customized proxy server id: "
set /p FP_PROXY_SERVER_KEYPAIR_PWD="[FP_PROXY_SERVER_KEYPAIR_PWD] Customized key pair password: "
set /p FP_PROXY_SERVER_FERNET_KEY="[FP_PROXY_SERVER_FERNET_KEY] Generated by admin/create_fernet_key.py: "

echo Generating key pair...
python admin\create_key_pair.py

echo Starting LiteLLM Proxy Server...
litellm --config config.yaml --port 4000