#!/bin/bash
set -e

echo "Changing to the target directory..."
cd ../../../

echo "Checking if virtual environment already exists..."
if [ -d ".venv" ]; then
    echo ".venv already exists, skipping creation."
else
    echo "Creating Python virtual environment..."
    python3 -m venv .venv
fi

echo "Activating virtual environment..."
source .venv/bin/activate

echo "Installing dependencies..."
pip install -r requirements-linux.txt

echo "Setting environment variables..."
export LITELLM_MODE=PRODUCTION
export FP_APP_BASE_URL=https://www.flexiproxy.com
export FP_PROXY_SERVER_URL=https://test.flexiproxy.com
export FP_PROXY_SERVER_ADVANCED=0
export FP_PROXY_SERVER_KEYPAIR_DIR=../key

read -p "[FP_APP_TOKEN_PASS] Issued by flexi-proxy admin/token-issuance.ts: " FP_APP_TOKEN_PASS
export FP_APP_TOKEN_PASS

read -p "[FP_PROXY_SERVER_ID] Customized proxy server id: " FP_PROXY_SERVER_ID
export FP_PROXY_SERVER_ID

read -p "[FP_PROXY_SERVER_KEYPAIR_PWD] Customized key pair password: " FP_PROXY_SERVER_KEYPAIR_PWD
export FP_PROXY_SERVER_KEYPAIR_PWD

read -p "[FP_PROXY_SERVER_FERNET_KEY] Generated by admin/create_fernet_key.py: " FP_PROXY_SERVER_FERNET_KEY
export FP_PROXY_SERVER_FERNET_KEY

echo "Generating key pair..."
python3 admin/create_key_pair.py

echo "Starting LiteLLM Proxy Server..."
nohup litellm --config config.yaml --port 80 &